######################################################################
# Automatically generated by qmake (3.0) jeu. juin 23 20:58:39 2016
######################################################################

TEMPLATE = app
TARGET = clock
INCLUDEPATH += .
QT += quick

# Input
SOURCES += main.cpp
